smoke_test:
 docker:
   - image: alpine:latest
 steps:
   - run: apk add --update curl
   - checkout
   - add_ssh_keys:
          fingerprints: ["f9:b5:94:9a:a0:6e:59:d3:97:1c:b6:4c:a0:3c:ec:8a"] 
   - run:
       name: smoke test
       command: |
         URL="https://blog.udacity.com/"
         # Test if website exists
         if curl -s --head ${URL} 
         then
           return 0
         else
           return 1
         fi
workflows:
  # Name the workflow "welcome"
  smoketest_workflow:
    # Run the welcome/run job in its own container
    jobs:
   
      - smoke_test
